### ISSUE TITLE
Broken resource returned twice to the pool

### ISSUE THREAD

**Issue by mballoni** [pivotalsoftware/session-managers#15]
Making some crash tests I noted that broken resources are returned twice to the pool:
 https://github.com/pivotalsoftware/session-managers/blob/master/redis-store/src/main/java/com/gopivotal/manager/redis/JedisTemplate.java#L42

 Checking the jedis docs I came across this issue that explains the problem as well as the solution description:
 https://github.com/xetorthio/jedis/issues/476

 Do you agree with this issue? I only ask because the tests requires it to be returned twice (one broken and one "normal").

 I would gladly make a pull request to fix this, can I? I just checked the contribution guidelines.

**Comment by jkonicki** [comment]
mballoni,

Yes, this needs to be handled properly.  Please create a PR and we will take a look at it for merging.

Thank you.

**Comment by mballoni** [comment]
Great, working on it.

 Also, would you mind if I update the Jedis version?
 It would be great to use some new features such as the java 7 auto closable try-with-resources.

 Thank you.

**Comment by mballoni** [comment]
Doing some integration tests right now, but you already can see the changes at the last two commits right here at my fork:

https://github.com/mballoni/session-managers/commits/master

**Comment by mballoni** [comment]
PR opened:
https://github.com/pivotalsoftware/session-managers/pull/17

**Comment by mballoni** [comment]
PR merged. Thanks!
