### ISSUE TITLE
add redis key prefix

### ISSUE THREAD

**Issue by andirdju** [pivotalsoftware/session-managers#2]
I'd like to suggest a new feature.

To be able to specify a redis key prefix, make it easier to flush all sessions for specific apps/context.

If you think that's a good idea I'll work on a pull request for it.

**Comment by nebhale** [comment]
In truth, I wouldn't expect any real improvements to be made on this project at this point.  Instead, we're recommending that applications use the [Spring Session][https://github.com/spring-projects/spring-session] project for their session replication needs.
