### ISSUE TITLE
IDE configuration files committed to repository

### ISSUE THREAD

**Issue by ccheetham** [pivotalsoftware/session-managers#24]
Project shouldn't contain IDE configuration files.  Remove IDE-specific configuration/state files, such as IntelliJ's `.idea` directory.

**Comment by mballoni** [comment]
I vote this up also for the branch 1.2.x.
Another issue about this branch is the sonar build failure, should I open another issue for that?

**Comment by ccheetham** [comment]
re branch: Targeting 1.2.x seems reasonable.  I don't think we'll release just for this, but it'll ease development.

re Sonar: please go ahead and open a separate issue
