### ISSUE TITLE
Sonar broken on 1.2.x branch

### ISSUE THREAD

**Issue by mballoni** [pivotalsoftware/session-managers#27]
The last two builds failed for the branch 1.2.x:

https://github.com/pivotalsoftware/session-managers/commits/1.2.x

 I was looking for some changes in the travis ci config file but couldn't figure what it was. I could only find a "connection timeout" in the build log:
https://travis-ci.org/pivotalsoftware/session-managers/jobs/207427149

**Comment by jkonicki** [comment]
I believe the Sonar DB is no longer available.  It was removed in master branch, needs to be removed in 1.2.x also.
