### ISSUE TITLE
consolidate 1.2 and 1.3 into a single code base

### ISSUE THREAD

**Issue by ccheetham** [pivotalsoftware/session-managers#30]
1.3 introduced support for Tomcat 8.5 (API changes).  These changes were intentionally kept separate for the purpose of expediency in resolving 8.5 incompatibilities.

However, at some point we should consolidate into a single codebase/release.

Several benefits:
  * reduce misconfiguration opportunity; for both deployments and dependent projects
  * simplify development by reducing merge workflow
  * help future-proof against Tomcat API changes; when API changes, framework will already be in place

A possible approach would:
  * create branch 1.3 for deprecated releases
    * 1.2 fixes merged to 1.3 if needed
    * 1.3 a deadend branch
  * create 2.0  branch (could remain `master`) for continuing development

**Comment by mballoni** [comment]
This looks a good idea.
 I mean, it could result in two artifacts onde for tomcat 7.x  and 8.x and another for 8.5 and superior.
 This way every core functionality could be the same codebase.

**Comment by mballoni** [comment]
Quick questions, is this going to happen in the near future?
 Otherwise I'm thinking on porting the cluster support to 1.2.x.
 Regards!

**Comment by ccheetham** [comment]
No immediate time target.  Probably a month or so out.
