### ISSUE TITLE
Objects missing in session in non-sticky environment

### ISSUE THREAD

**Issue by stuartjackson23** [pivotalsoftware/session-managers#49]
I have moved my code onto an environment where I have two EC2 instances running Tomcat 8.0.24 being load balanced by ELB with stickiness disabled. The ELB switches between the two servers quite evenly. Both Tomcat instances are storing their sessions in an AWS ElastiCache Redis server.

What I'm finding is that objects stored in Redis are being lost, i.e. in one request I set a session attribute "myForm" (using redis-cli I can see that myForm is in the session). Then, a few minutes later I go to retrieve the object in another request and it's gone (as confirmed by redis-cli). I never remove the object from the session anywhere in my code and I've even set a breakpoint in Tomcat's StandardSessionFacade.removeAttribute() method and it never fires. 

Sorry this is a bit vague but this is a mature and complex application and it's very hard to provide you steps to recreate. I'm using the Spring framework and myForm uses the @SessionAttributes and @ModelAttribute annotations - don't know if that's relevant. 

If I disable one of the servers using the ELB (so that all traffic goes to a single server) everything works fine.

What could be useful is if I could get some debug info written to the logs for com.gopivotal. I tried adding "com.gopivotal.level = FINE" to the $TOMCAT/conf/logging.properties file but this didn't do anything.

Here are my configuration files (same on both servers). Thanks very much for your help!

**$TOMCAT/conf/context.xml**
```
<?xml version='1.0' encoding='utf-8'?>

<Context>

    <WatchedResource>WEB-INF/web.xml</WatchedResource>
    <WatchedResource>${catalina.base}/conf/web.xml</WatchedResource>

    <!-- Start of additions by SJ for Redis integration -->
    <Valve className="com.gopivotal.manager.SessionFlushValve"/>

    <Manager className="org.apache.catalina.session.PersistentManager">
        <Store className="com.gopivotal.manager.redis.RedisStore"
            host="my-redis-cache.icdzqp.ng.0001.apse2.cache.amazonaws.com"
            database="2"
            connectionPoolSize="100"
            timeout="10000"
        />
    </Manager>
    <!-- End of additions by SJ for Redis integration -->

</Context>
```
**$TOMCAT/conf/server.xml**
```
<?xml version='1.0' encoding='utf-8'?>
<Server port="8005" shutdown="SHUTDOWN">
  <Listener className="org.apache.catalina.startup.VersionLoggerListener" />
  <!--APR library loader. Documentation at /docs/apr.html -->
  <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
  <!-- Prevent memory leaks due to use of particular java/javax APIs-->
  <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
  <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
  <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener" />

  <GlobalNamingResources>
    <Resource name="UserDatabase" auth="Container"
              type="org.apache.catalina.UserDatabase"
              description="User database that can be updated and saved"
              factory="org.apache.catalina.users.MemoryUserDatabaseFactory"
              pathname="conf/tomcat-users.xml" />
  </GlobalNamingResources>

  <Service name="Catalina">

    <Connector port="8080" protocol="HTTP/1.1" compression="on" noCompressionUserAgents="gozilla, traviata" scheme="https"
               proxyPort="443" proxyHost="localhost" connectionTimeout="20000" redirectPort="443" />

    <Connector port="8009" protocol="AJP/1.3" redirectPort="8443" />

    <Engine name="Catalina" defaultHost="localhost">
      <Realm className="org.apache.catalina.realm.LockOutRealm">
        <Realm className="org.apache.catalina.realm.UserDatabaseRealm" resourceName="UserDatabase"/>
      </Realm>

      <Host name="localhost"  appBase="webapps" unpackWARs="true" autoDeploy="true">

        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log" suffix=".txt"
               maxLogMessageBufferSize="512"
               pattern="%h %l %u %t &quot;%r&quot; %s %b %D %F" />

      </Host>
    </Engine>
  </Service>
</Server>
```
**$TOMCAT/conf/Catalina/localhost/ROOT.xml**
```
<Context
        docBase="/opt/MyApp/lba/my.war"
        unpackWAR="true"
        privileged="true"
        antiResourceLocking="false"
        reloadable="false">

      <Resource   name="jdbc/ConfigDB"
                 auth="Container"
                 type="javax.sql.DataSource"
                 maxTotal="5"
                 maxIdle="10"
                 maxWaitMillis="10000"
                 username="user"
                 password="password"
                 driverClassName="oracle.jdbc.driver.OracleDriver"
                 url="jdbc:oracle:thin:@10.222.5.30:1521:xe" />

        <Environment name="application" type="java.lang.String" value="common"/>
        <Environment name="environment" type="java.lang.String" value="staging"/>
        <Parameter name="log.file" value="/logconfig/log4j.xml" override="false"/>

</Context>
```

**Comment by stuartjackson23** [comment]
Thinking about it some more I think a good plan would be for me to download the source and debug to see what's going on. I suspect that sessions from one of the Tomcat instances are clobbering the sessions of the other. Can you tell me a good place to put a breakpoint in the code to see when the session is being written to/read from redis. Is it in the SessionFlushValve invoke method?

**Comment by stuartjackson23** [comment]
The problem seems to be that Tomcat is not always loading the session from the Redis store for each request. Instead it's getting the session from  memory (sessions attribute in ManagerBase). How can I force Tomcat to load the session from the store every time? Without this things don't work in a non-sticky environment.

**Comment by stuartjackson23** [comment]
Hi Chris, I'd really appreciate your input on this. Other implementations I've looked at for storing Tomcat sessions in Redis write their own Manager which allows them to control the loading of the sessions from the store. eg. in jcoleman's implementation he says ["Sessions are loaded as requested directly from Redis (but subsequent requests for the session during the same request context will return a ThreadLocal cache rather than hitting Redis multiple times.)"](https://github.com/jcoleman/tomcat-redis-session-manager).

If I can't guarantee that the session will be loaded from the Redis store with each request then things just don't work in a non-sticky environment, which is surely one of the drivers for storing the session in Redis (it was for me anyway). Thanks!

**Comment by gtors** [comment]
Hi, @stuartjackson23!  
As I understand, you're now using `jcoleman/tomcat-redis-session-manager`. If so, can you please share your experience of using it? Did it solve your issue? Have you encountered any other problems during use?

**Comment by stuartjackson23** [comment]
We have done some initial testing with jcoleman's implementation but haven't moved forward with it yet to production. We haven't found any issues so far. 

I was hoping that someone was going to tell me that I was doing something wrong with the pivotal implementation as I'd rather stick with it since it's more actively developed and it supports Tomcat 8 which we're currently on.

**Comment by ccheetham** [comment]
@stuartjackson23 I've got some cycles to spend on this issue this.  Are you still having problems as noted in your initial post>

**Comment by stuartjackson23** [comment]
Hi Chris, Yes I couldn't get past these issues. It would be great if you could have a look at it.

**Comment by sdwr98** [comment]
Hi all - I'm seeing this issue as well.  We had been using the `jcoleman/tomcat-redis-session-manager`, but came across an edge case where it was breaking due to the use of the ThreadLocal storage.  We have been testing with this implementation, but I'm now running into an issue very similar to the one described in this bug. 

I'm happy to help if I can in tracing what's going on.

**Comment by sdwr98** [comment]
Well, for what it's worth - it appears that the Tomcat PersistentManager is *not* intended to be used for what @stuartjackson23 and I are trying to use it for, namely storing all session data outside of Tomcat and loading it for every request.  The `tomcat-redis-session-manager` provides its own Manager interface for this very reason. 

I think what I'm going to have to do is go fix my edge case in that codebase rather than using this one.  I'll post here if anybody wants the updated version.
