### ISSUE TITLE
session ttl always set to -1

### ISSUE THREAD

**Issue by thdghgns** [pivotalsoftware/session-managers#9]
my redis session's ttl always set to -1
using session-managers-1.2.0.RELEASE.
and my tomcat is 7.0.67
my server is on aws ec2 machine (amazon linux)

I check time property is set right. but ttl set to -1...
(check by logging at RedisStore.java )

 someone help plz.
- it expires... but not expected like i set in the context.xml...

**Comment by toukovk** [comment]
At least on [RedisStore:save](https://github.com/pivotalsoftware/session-managers/blob/master/redis-store/src/main/java/com/gopivotal/manager/redis/RedisStore.java#L526) there is set but no expire?

I don't know Redis too well but maybe there should be either expire after set or setex? (Based on some setting)

**Comment by jkonicki** [comment]
We have merged PR for this. Closing ticket. Thanks.
